// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    GgSpinner: typeof import('~icons/gg/spinner')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    RandomButton: typeof import('./src/components/RandomButton.vue')['default']
    RandomForm: typeof import('./src/components/RandomForm.vue')['default']
    RandomInput: typeof import('./src/components/RandomInput.vue')['default']
  }
}

export {}
