// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    FabButton: typeof import('./src/components/FabButton.vue')['default']
    FabCheckbox: typeof import('./src/components/FabCheckbox.vue')['default']
    FabField: typeof import('./src/components/FabField.vue')['default']
    FabForm: typeof import('./src/components/FabForm.vue')['default']
    FabInput: typeof import('./src/components/FabInput.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconGgSpinner: typeof import('~icons/gg/spinner')['default']
  }
}

export {}
