// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    FabButton: typeof import('./src/components/FabButton.vue')['default']
    FabCheckbox: typeof import('./src/components/FabCheckbox.vue')['default']
    FabField: typeof import('./src/components/FabField.vue')['default']
    FabForm: typeof import('./src/components/FabForm.vue')['default']
    FabHidden: typeof import('./src/components/FabHidden.vue')['default']
    FabInput: typeof import('./src/components/FabInput.vue')['default']
    FabLabel: typeof import('./src/components/FabLabel.vue')['default']
    FabMultiSelect: typeof import('./src/components/FabMultiSelect.vue')['default']
    FabSelect: typeof import('./src/components/FabSelect.vue')['default']
    FabSlider: typeof import('./src/components/FabSlider.vue')['default']
    FabTextarea: typeof import('./src/components/FabTextarea.vue')['default']
    FabToggle: typeof import('./src/components/FabToggle.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconGgSpinner: typeof import('~icons/gg/spinner')['default']
  }
}

export {}
